// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorthShift.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NorthShift.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412180406_FixEnumValues")]
    partial class FixEnumValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NorthShift.Api.Models.AlertSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContractLengths")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguagePref")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Languages")
                        .HasColumnType("text");

                    b.Property<string>("Provinces")
                        .HasColumnType("text");

                    b.Property<string>("RoleTypes")
                        .HasColumnType("text");

                    b.Property<string>("UnsubscribeToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AlertSubscriptions");
                });

            modelBuilder.Entity("NorthShift.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("AppUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NorthShift.Api.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicantEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AvailabilityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CoverMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecruiterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResumeS3Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountManagerId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ListingId");

                    b.HasIndex("RecruiterId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("NorthShift.Api.Models.ApplicationNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WrittenByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("WrittenByUserId");

                    b.ToTable("ApplicationNotes");
                });

            modelBuilder.Entity("NorthShift.Api.Models.ApplicationStatusLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("ApplicationStatusLogs");
                });

            modelBuilder.Entity("NorthShift.Api.Models.Licence", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Expiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenceNumber")
                        .HasColumnType("text");

                    b.HasKey("ApplicationId", "Province");

                    b.ToTable("Licences");
                });

            modelBuilder.Entity("NorthShift.Api.Models.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Community")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContractLength")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionFr")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<bool>("HousingProvided")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PayMax")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("PayMin")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("PostedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RecruiterId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleFr")
                        .HasColumnType("text");

                    b.Property<bool>("TravelCovered")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AccountManagerId");

                    b.HasIndex("OrgId");

                    b.HasIndex("PostedByUserId");

                    b.HasIndex("RecruiterId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("NorthShift.Api.Models.NurseEmailConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConsentIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConsentedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SourceListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnsubscribeToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("NurseEmailConsents");
                });

            modelBuilder.Entity("NorthShift.Api.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAnnual")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("NorthShift.Api.Models.Admin", b =>
                {
                    b.HasBaseType("NorthShift.Api.Models.AppUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("NorthShift.Api.Models.OrgUser", b =>
                {
                    b.HasBaseType("NorthShift.Api.Models.AppUser");

                    b.Property<string>("InviteToken")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.HasIndex("OrgId");

                    b.HasDiscriminator().HasValue("OrgUser");
                });

            modelBuilder.Entity("NorthShift.Api.Models.AccountManager", b =>
                {
                    b.HasBaseType("NorthShift.Api.Models.OrgUser");

                    b.Property<string>("BillingEmail")
                        .HasColumnType("text");

                    b.Property<string>("BillingName")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("AccountManager");
                });

            modelBuilder.Entity("NorthShift.Api.Models.Recruiter", b =>
                {
                    b.HasBaseType("NorthShift.Api.Models.OrgUser");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Recruiter");
                });

            modelBuilder.Entity("NorthShift.Api.Models.Application", b =>
                {
                    b.HasOne("NorthShift.Api.Models.AccountManager", null)
                        .WithMany("AssignedApplications")
                        .HasForeignKey("AccountManagerId");

                    b.HasOne("NorthShift.Api.Models.AppUser", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NorthShift.Api.Models.Listing", "Listing")
                        .WithMany("Applications")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NorthShift.Api.Models.Recruiter", null)
                        .WithMany("AssignedApplications")
                        .HasForeignKey("RecruiterId");

                    b.Navigation("AssignedTo");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("NorthShift.Api.Models.ApplicationNote", b =>
                {
                    b.HasOne("NorthShift.Api.Models.Application", "Application")
                        .WithMany("Notes")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NorthShift.Api.Models.OrgUser", "WrittenBy")
                        .WithMany()
                        .HasForeignKey("WrittenByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("WrittenBy");
                });

            modelBuilder.Entity("NorthShift.Api.Models.ApplicationStatusLog", b =>
                {
                    b.HasOne("NorthShift.Api.Models.Application", "Application")
                        .WithMany("StatusLogs")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NorthShift.Api.Models.AppUser", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ChangedBy");
                });

            modelBuilder.Entity("NorthShift.Api.Models.Licence", b =>
                {
                    b.HasOne("NorthShift.Api.Models.Application", null)
                        .WithMany("Licences")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NorthShift.Api.Models.Listing", b =>
                {
                    b.HasOne("NorthShift.Api.Models.AccountManager", null)
                        .WithMany("Listings")
                        .HasForeignKey("AccountManagerId");

                    b.HasOne("NorthShift.Api.Models.Organization", "Org")
                        .WithMany("Listings")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NorthShift.Api.Models.AppUser", "PostedBy")
                        .WithMany()
                        .HasForeignKey("PostedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NorthShift.Api.Models.Recruiter", null)
                        .WithMany("Listings")
                        .HasForeignKey("RecruiterId");

                    b.Navigation("Org");

                    b.Navigation("PostedBy");
                });

            modelBuilder.Entity("NorthShift.Api.Models.OrgUser", b =>
                {
                    b.HasOne("NorthShift.Api.Models.Organization", "Org")
                        .WithMany("Users")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Org");
                });

            modelBuilder.Entity("NorthShift.Api.Models.Application", b =>
                {
                    b.Navigation("Licences");

                    b.Navigation("Notes");

                    b.Navigation("StatusLogs");
                });

            modelBuilder.Entity("NorthShift.Api.Models.Listing", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("NorthShift.Api.Models.Organization", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NorthShift.Api.Models.AccountManager", b =>
                {
                    b.Navigation("AssignedApplications");

                    b.Navigation("Listings");
                });

            modelBuilder.Entity("NorthShift.Api.Models.Recruiter", b =>
                {
                    b.Navigation("AssignedApplications");

                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
